# Generated by Django 5.2.15 on 2026-06-15 13:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("hackathon", "Hackathon"),
                            ("conference", "Conference"),
                            ("webinar", "Webinar"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=2)),
                (
                    "continent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Africa", "Africa"),
                            ("Antarctica", "Antarctica"),
                            ("Asia", "Asia"),
                            ("Europe", "Europe"),
                            ("North America", "North America"),
                            ("Oceania", "Oceania"),
                            ("South America", "South America"),
                        ],
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SavedSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "filters",
                    models.JSONField(
                        default=dict,
                        help_text="JSON dict of filter criteria applied to the Person table.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_segments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "saved segment",
                "verbose_name_plural": "saved segments",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_dt", models.DateTimeField(blank=True, null=True)),
                ("end_dt", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "ordering": ["start_dt", "name"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("attendee", "Attendee"),
                            ("speaker", "Speaker"),
                            ("organizer", "Organizer"),
                            ("facilitator", "Facilitator"),
                            ("reviewer", "Reviewer"),
                            ("panelist", "Panelist"),
                            ("observer", "Observer"),
                        ],
                        default="attendee",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("waitlisted", "Waitlisted"),
                            ("attended", "Attended"),
                            ("no_show", "No-show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="events.event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="core.person",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participations",
                        to="events.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "participation",
                "verbose_name_plural": "participations",
                "ordering": ["person__family_name", "person__given_name"],
                "constraints": [
                    models.UniqueConstraint(fields=("person", "event"), name="unique_person_event")
                ],
            },
        ),
    ]
