# Generated by Django 5.2.15 on 2026-06-28 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="event_end_not_before_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_dt__isnull", True),
                    ("start_dt__isnull", True),
                    ("end_dt__gte", models.F("start_dt")),
                    _connector="OR",
                ),
                name="session_end_not_before_start",
            ),
        ),
    ]
