# Generated by Django 5.2.15 on 2026-06-14 12:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertiseTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("term", models.CharField(max_length=255, unique=True)),
                (
                    "source_vocabulary",
                    models.CharField(
                        choices=[
                            ("ENVO", "ENVO"),
                            ("PATO", "PATO"),
                            ("RO", "RO"),
                            ("CAMO", "CAMO"),
                            ("ELMO", "ELMO"),
                            ("OpenAlex", "OpenAlex"),
                            ("Wikidata", "Wikidata"),
                            ("GBIF", "GBIF"),
                            ("local", "Local"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "expertise term",
                "verbose_name_plural": "expertise terms",
                "ordering": ["term"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_normalized", models.CharField(blank=True, db_index=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=2)),
                (
                    "continent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Africa", "Africa"),
                            ("Antarctica", "Antarctica"),
                            ("Asia", "Asia"),
                            ("Europe", "Europe"),
                            ("North America", "North America"),
                            ("Oceania", "Oceania"),
                            ("South America", "South America"),
                        ],
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "org_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("university", "University"),
                            ("research_institute", "Research institute"),
                            ("ngo", "NGO"),
                            ("government", "Government"),
                            ("industry", "Industry"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ror_id", models.CharField(blank=True, max_length=50, verbose_name="ROR ID")),
                (
                    "metadata_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("needs_review", "Needs review"),
                            ("verified", "Verified"),
                            ("stale", "Stale"),
                            ("conflicting", "Conflicting"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="unreviewed",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("given_name", models.CharField(max_length=150)),
                ("family_name", models.CharField(max_length=150)),
                ("name_normalized", models.CharField(blank=True, db_index=True, max_length=301)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        help_text="ORCID iD in 0000-0000-0000-000X format",
                        max_length=19,
                        null=True,
                        unique=True,
                        verbose_name="ORCID",
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 code", max_length=2),
                ),
                (
                    "continent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Africa", "Africa"),
                            ("Antarctica", "Antarctica"),
                            ("Asia", "Asia"),
                            ("Europe", "Europe"),
                            ("North America", "North America"),
                            ("Oceania", "Oceania"),
                            ("South America", "South America"),
                        ],
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "notes_private",
                    models.TextField(blank=True, help_text="Admin-only. Never exported."),
                ),
                ("consent_contact", models.BooleanField(default=False)),
                ("consent_public_profile", models.BooleanField(default=False)),
                (
                    "metadata_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("needs_review", "Needs review"),
                            ("verified", "Verified"),
                            ("stale", "Stale"),
                            ("conflicting", "Conflicting"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="unreviewed",
                        max_length=20,
                    ),
                ),
                ("metadata_last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("metadata_last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
                "ordering": ["family_name", "given_name"],
            },
        ),
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=150)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affiliations",
                        to="core.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliations",
                        to="core.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "affiliation",
                "verbose_name_plural": "affiliations",
                "ordering": ["-is_primary", "-start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "organization"), name="unique_person_organization"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonExpertise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertise",
                        to="core.person",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_links",
                        to="core.expertiseterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "person expertise",
                "verbose_name_plural": "person expertise",
                "ordering": ["term__term"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "term"), name="unique_person_expertise"
                    )
                ],
            },
        ),
    ]
