# Generated by Django 5.2.15 on 2026-06-15 13:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ORCIDProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fetched_at", models.DateTimeField()),
                ("given_name_remote", models.CharField(blank=True, max_length=150)),
                ("family_name_remote", models.CharField(blank=True, max_length=150)),
                ("raw_record", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orcid_profile",
                        to="core.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "ORCID profile",
                "verbose_name_plural": "ORCID profiles",
            },
        ),
        migrations.CreateModel(
            name="ORCIDWork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("put_code", models.IntegerField()),
                ("title", models.CharField(blank=True, max_length=500)),
                ("work_type", models.CharField(blank=True, max_length=100)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("raw_work", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orcid_works",
                        to="core.person",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="core.orcidprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ORCID work",
                "verbose_name_plural": "ORCID works",
                "ordering": ["-publication_year", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "put_code"), name="unique_person_put_code"
                    )
                ],
            },
        ),
    ]
