# Generated by Django 5.2.15 on 2026-06-15 15:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_orcid_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("title_normalized", models.CharField(blank=True, db_index=True, max_length=500)),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("doi_normalized", models.CharField(blank=True, db_index=True, max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("publication_type", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "publication",
                "verbose_name_plural": "publications",
                "ordering": ["-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("publication_count", models.PositiveIntegerField(default=1)),
                ("first_year", models.IntegerField(blank=True, null=True)),
                ("last_year", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations_as_a",
                        to="core.person",
                    ),
                ),
                (
                    "person_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations_as_b",
                        to="core.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "collaboration",
                "verbose_name_plural": "collaborations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person_a", "person_b"), name="unique_collaboration_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Authorship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        help_text="Name as it appeared; may be unlinked to a Person.",
                        max_length=300,
                    ),
                ),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorships",
                        to="core.person",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to="core.publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "authorship",
                "verbose_name_plural": "authorships",
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("person__isnull", False)),
                        fields=("publication", "person"),
                        name="unique_publication_person_authorship",
                    )
                ],
            },
        ),
    ]
