# Generated by Django 5.2.15 on 2026-06-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_org_wikidata_qid_pub_venue"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collaboration",
            constraint=models.CheckConstraint(
                condition=models.Q(("person_a", models.F("person_b")), _negated=True),
                name="collaboration_people_differ",
            ),
        ),
    ]
