# Generated by Django 5.2.15 on 2026-06-15 00:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=5.0,
                        help_text="Points deducted from quality score (0–100) per open issue.",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("person", "Person"), ("organization", "Organization")],
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "metadata check",
                "verbose_name_plural": "metadata checks",
                "ordering": ["target", "severity", "code"],
            },
        ),
        migrations.CreateModel(
            name="MetadataFreshnessRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "max_age_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Flag the record stale if not updated within this many days.",
                    ),
                ),
                (
                    "metadata_check",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freshness_rule",
                        to="metadata.metadatacheck",
                    ),
                ),
            ],
            options={
                "verbose_name": "freshness rule",
                "verbose_name_plural": "freshness rules",
            },
        ),
        migrations.CreateModel(
            name="MetadataIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, help_text="Human-readable explanation of why this was flagged."
                    ),
                ),
                ("suggested_fix", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("ignored_at", models.DateTimeField(blank=True, null=True)),
                ("ignore_reason", models.TextField(blank=True)),
                (
                    "ignored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ignored_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "metadata_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="metadata.metadatacheck",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_issues",
                        to="core.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_issues",
                        to="core.person",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "metadata issue",
                "verbose_name_plural": "metadata issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetadataVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("verified_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="core.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="core.person",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "metadata verification",
                "verbose_name_plural": "metadata verifications",
                "ordering": ["-verified_at"],
            },
        ),
    ]
