# Generated by Django 5.2.15 on 2026-06-15 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_publication_authorship_collaboration"),
        ("metadata", "0004_seed_orcid_checks"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadataissue",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_issues",
                to="core.publication",
            ),
        ),
        migrations.AlterField(
            model_name="metadatacheck",
            name="target",
            field=models.CharField(
                choices=[
                    ("person", "Person"),
                    ("organization", "Organization"),
                    ("publication", "Publication"),
                ],
                max_length=20,
            ),
        ),
    ]
