# Generated by Django 5.2.15 on 2026-06-28 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_collaboration_collaboration_people_differ"),
        ("metadata", "0007_suggestion_publication_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="metadatacheck",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gte", 0), ("weight__lte", 100)),
                name="metadata_check_weight_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="metadataissue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("organization__isnull", True),
                        ("person__isnull", False),
                        ("publication__isnull", True),
                    ),
                    models.Q(
                        ("organization__isnull", False),
                        ("person__isnull", True),
                        ("publication__isnull", True),
                    ),
                    models.Q(
                        ("organization__isnull", True),
                        ("person__isnull", True),
                        ("publication__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="metadata_issue_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="metadatasuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence_score__gte", 0), ("confidence_score__lte", 1)),
                name="metadata_suggestion_confidence_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="metadatasuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("organization__isnull", True),
                        ("person__isnull", False),
                        ("publication__isnull", True),
                    ),
                    models.Q(
                        ("organization__isnull", False),
                        ("person__isnull", True),
                        ("publication__isnull", True),
                    ),
                    models.Q(
                        ("organization__isnull", True),
                        ("person__isnull", True),
                        ("publication__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="metadata_suggestion_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="metadataverification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("organization__isnull", True), ("person__isnull", False)),
                    models.Q(("organization__isnull", False), ("person__isnull", True)),
                    _connector="OR",
                ),
                name="metadata_verification_exactly_one_target",
            ),
        ),
    ]
