# Generated by Django 5.2.15 on 2026-06-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importsession",
            name="file_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="importsession",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
